alias ni='npm install'
alias ns='npm start'
alias nr='npm run'
alias nb='npm run build'
alias nt='npm test'
alias nu='npm update'
alias yb='yarn build'
alias yk='yarn storybook'
alias yl='yarn lint'
alias ys='yarn start'
alias yt='yarn test'
alias dcnpm='docker-compose run --rm ${APP:-app} npm'
alias dcnpx='docker-compose run --rm ${APP:-app} npx'

alias tsc='yarn tsc'
alias eslint='yarn eslint'
alias prettier='yarn prettier'
alias ts-node='yarn ts-node'
